CC=gcc-4.1

CFLAGS = -Wall -O3 -std=gnu89 -pedantic-errors
HEADERS = -I./
all : programa programa2

programa: funciones.h 
	$(CC) -o programa main.c funciones.c $(CFLAGS) $(HEADERS)

programa2: funciones.h 
	$(CC) -o programa2 main2.c $(CFLAGS) $(HEADERS)

clean: 
	rm -rf *o programa programa2
